name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      if: hashFiles('setup.py')
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Cache playwright 
      uses: actions/cache@v3
      with: 
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Cache Spotify info
      uses: actions/cache@v3
      with: 
        path: ~/.config/esporifai
        key: ${{ runner.os }}-spotify
    - name: Install dependencies
      if: hashFiles('setup.py')
      run: |
        pip install -e '.[test]'
        playwright install chromium
    - name: Top Artist
      run: |
        esporifai get-top artists --limit 1 --trim --output - | jq '.[0].name'
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
    - name: Run tests
      if: hashFiles('setup.py')
      run: |
        pytest
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
